Completely refactor main
Main is responsible for iterating through direcctories and passing a
target and its output path to contate_files

diff --git a/main b/main
--- a/main
+++ b/main
@@ -1,136 +1,132 @@
 #!/bin/bash
 
-d_start
-trap finish d_clean
+# BASIC INITIALIZATIONS
 
-while [ "$1" ] ; do
-	case "$1" in
-	'-i'|'--input')
-		TARGET="$2"
-		dbg "CMD: $TARGET"
-		if [ -d "$TARGET" ]; then
-			export ROOT_INPUT_DIR="$(realpath "$TARGET")"
-		fi
-		shift 2
+shopt -s nullglob globstar
+
+# An array of all the variables we've created
+declare -a CONTATE_TEMP_FILE_LIST
+
+# contate_clean is a function to delete those temps and call dictionary's clean too, which celetes the variable temp
+function contate_clean {
+	d_clean
+	for file in "${CONTATE_TEMP_FILE_LIST[@]}"; do
+		dbg "rm'ing $file"
+		rm "$file"
+	done
+}
+dbg "d_start()"
+d_start
+dbg "trap contate_clean()"
+trap contate_clean EXIT
+
+# SET VARIABLES
+
+def CONTATE_RECURSE false
+def CONTATE_QUIET false
+def CONTATE_PATTERN '(.*).contate$'
+def CONTATE_DRY false
+export CONTATE_QUIET CONTATE_RECURSE CONTATE_PATTERN CONTATE_OUTPUT CONTATE_DRY
+
+while getopts ":o:p:dqrh" opt; do
+	dbg "Getopts iteration"
+	case "$opt" in
+	d)
+		CONTATE_DRY=true
 		;;
-	'--clear')
-			unset OUTPUT
-			unset PRINT
-			unset RECURSE
-			unset DEBUG
-			unset QUIET
-			unset COPY_ARG
-			unset EXCLUDE
+	o)
+		CONTATE_OUTPUT="${OPTARG}"
 		;;
-	'-o'|'--output')
-		export OUTPUT="$2"
-		if  test ! -f "$OUTPUT" && test ! -d "$OUTPUT"; then
-			if [ ! -d "$(dirname "$OUTPUT")" ]; then
-				usage "Output is neither file nor directory"
-			fi
-		fi
-		unset PRINT
-		shift 2
+	r)
+		CONTATE_RECURSE=true
 		;;
-	'-p'|'--print')
-		export PRINT=true
-		unset OUTPUT	
-		shift 1
+	p)
+		CONTATE_PATTERN="${OPTARG}"
 		;;
-	'-r'|'--recursive')
-		export RECURSE=true
-		shift 1
+	q)
+		CONTATE_QUIET=true
 		;;
-	'-d'|'--debug')
-		export DEBUG=true	
-		shift 1
-		;;
-	'-e'|'--exclude')
-		export EXCLUDE="$2"
-		shift 2
-		;;
-	'-q'|'--quiet')
-		export QUIET=true
-		shift 1
-		;;
-	# contate expects to take a target, and then process it, this seems silly
-	'-s'|'--script')
-		SCRIPTDIR="$2"
-		shift 2
-		;;
-	'-v'|'--var')
-		VARIABLE_ARG="$2"
-		VARIABLE_ARG2="$3"
-		if [ -n "$VARIABLE_ARG2" ]; then
-			shift 3	
-		else
-			shift 2
-		fi
-		;;
-	'-c'|'--copy')
-		export COPY_ARG+="$2"
-		shift 2
+	h)
+		CONTATE_QUIET=false
+		usage
+		exit 0
 		;;
 	*)
-		usage "Usage: What is this that came through your arguments: $1"	
-	;;
+		err	"Unkown opt: $OPTARG"
+		usage 
+		exit 1
+		;;
 	esac
 done
 
-#add a way to copy all non-ascii files automatically
-if test -z "$PRINT" && test -z "$OUTPUT" && test -z "$VARIABLE_ARG"; then
-	usage "You need to specify file output (-o) or stdout (-p) or variable (-v)"
-elif test -z "$TARGET" && test -z "$SCRIPTDIR" && test -z "$VARIABLE_ARG" ; then
-	usage "You need either an input file (-i) a script to \
-					run (-s) or a variable to un/set (-v)"
-elif [ -f "${TARGET}" ];	then
-	if [ -d "${OUTPUT}" ]; then
-		COPIED_PATH=""
-		if [ -n "$ROOT_INPUT_DIR" ]; then
-			COPIED_PATH="$(sed "s|${ROOT_INPUT_DIR}||" <<< "$(dirname "$(realpath "$TARGET")")" )"/
-			dbg "Copied_path = $COPIED_PATH"
-		fi
-		mkdir -p "${OUTPUT}"/"${COPIED_PATH}"
-		SPECIFIC_OUTPUT="${OUTPUT}"/"${COPIED_PATH}""$(basename "${TARGET}")"
-	else
-		SPECIFIC_OUTPUT="${OUTPUT}"
-	fi
-	dbg "Output=$OUTPUT and Specific Output=$SPECIFIC_OUTPUT or Print=$PRINT"
-	if cmp "$(realpath "${TARGET}")" "$COPY_ARG"; then
-		dbg "cpy $TARGET"$'\n'
-		if test ! "$PRINT" = true; then
-			cp -up "${TARGET}" "${SPECIFIC_OUTPUT}"
-		else
-			cat "${TARGET}"
-		fi
-	elif file "${TARGET}" | grep ASCII -qI &>/dev/null; then
-		contate_file "${TARGET}" "${SPECIFIC_OUTPUT}"
-	elif test "$COPY_ALL_NASCII" = true && test ! "${PRINT}" = true; then
-		dbg "copy because not ascii"
-		cp -up "${TARGET}" "${SPECIFIC_OUTPUT}"	
-	else
-		err "Found non-ascii files to be contated without \
-					a flag to copy all non-ascii files or tried to \
-					print a non-ascii file"
-	fi
-elif test -d "${TARGET}" ; then
-	if test -n "${OUTPUT}" && test ! -d "${OUTPUT}"; then
-		usage "Target is a directory, so output must be a directory or empty w/ --print"
-	elif test ! "${RECURSE}" = true;	then
-		usage "Target is a directory, set -r"
-	fi
-	find "$(realpath "${TARGET}")" -name '*' -not -path '*/\.*' -not -name 'Makefile' -not -name '*.contate' -not -path '*/*contate/*' -type f $EXCLUDE -exec "${0}" -i {} \;
-# not the way to handle variable args
-elif [ -n "$VARIABLE_ARG" ]; then
-	if [ -n "$VARIABLE_ARG2" ]; then
-		setvar "$VARIABLE_ARG" "$VARIABLE_ARG2"
-	else
-		getvar "$VARIABLE_ARG"
-	fi
-elif [ -n "$SCRIPTDIR" ]; then
-	exit "This is not supported yet and I don't know why I thought I needed it"
+dbg "All arguments passed:: ${*}"	
+
+shift "$(( OPTIND - 1 ))"
+
+dbg "CONTATE_DRY=${CONTATE_DRY}"
+dbg "CONTATE_OUTPUT=${CONTATE_OUTPUT}"
+dbg "CONTATE_RECURSE=${CONTATE_RECURSE}"
+dbg "CONTATE_DEBUG=${CONTATE_DEBUG}"
+dbg "CONTATE_QUIET=${CONTATE_QUIET}"
+dbg "CONTATE_PATTERN=${CONTATE_PATTERN}"
+dbg "CONTATE FILES: ${*}"
+
+# VALIDATE FLAGS
+
+if ${CONTATE_QUIET} && ${CONTATE_DEBUG}; then
+	err "You cannot set both quiet and debug"
+	exit 1
 fi
 
-if [ "$TMP_OWNER" = true ]; then
-	rm "$TMP_VAR"
+if [[ -d "${CONTATE_OUTPUT}" ]]; then
+	if [[ -w "${CONTATE_OUTPUT}" ]]; then
+		dbg "CONTATE_OUTPUT is a directory"
+		CONTATE_OUTPUT="$(realpath "${CONTATE_OUTPUT}")"
+	else
+		err "Can't write to ${CONTATE_OUTPUT}"
+		exit 1
+	fi
+elif [ -z "${CONTATE_OUTPUT}" ] || [ "${CONTATE_OUTPUT}" = "/dev/stdout" ]; then
+	dbg "CONTATE_OUTPUT not set, so stdout"
+	CONTATE_OUTPUT="/dev/stdout"
+else
+	err "Contate cannot currently create directories or use a custom naming scheme for files beyond -p"
+	usage
+	exit
 fi
+dbg "CONTATE_OUTPUT reset to: ${CONTATE_OUTPUT}"
+
+for target; do
+	if [[ -d "${target}" ]] && ! $CONTATE_RECURSE; then
+		err "${target} is a directory but didn't specify -r"
+		usage
+		exit 1
+	fi
+done
+
+# RECURSE THROUGH INPUTS
+for target; do
+	if [ "$CONTATE_MASTER" = "$$" ]; then
+		export REMOVEABLE_PATH="$(dirname $target)"/
+	fi
+	if [[ -d "${target}" && -x "${target}" && -r "${target}" ]]; then
+		dbg "TARGET DIRECTORY: ${target}"
+		${0} ${target}/*
+	elif [[ -f "${target}" && -r "${target}" ]]; then
+		dbg "TARGET FILE: ${target}"
+		if [[ "${target}" =~ ${CONTATE_PATTERN} ]]; then
+			if [ "${CONTATE_OUTPUT}" != "/dev/stdout" ]; then
+				if [ -n "${BASH_REMATCH[1]}" ]; then
+					OUTPUT_SUBPATH="${BASH_REMATCH[1]#${REMOVABLE_PATH}}"
+				else
+					OUTPUT_SUBPATH="${target#${REMOVABLE_PATH}}"
+				fi
+				CONTATE_OUTPUT="${CONTATE_OUTPUT}/${OUTPUT_SUBPATH}"
+				dbg "Is a contate file! it's output is: ${CONTATE_OUTPUT}"
+			fi
+			if ! $CONTATE_DRY; then 
+				contate_file "$(realpath ${target})" "${CONTATE_OUTPUT}" 
+			fi
+		fi
+	fi
+done
